"""FemMHC: female-specialized wearable foundation model research package."""

from .heads import ClassificationHead, OrdinalHead, ProbabilisticOutput, RegressionHead
from .model import (
    FemMHCEncoder,
    FemMHCOutput,
    LifecycleAdapterBank,
    LowRankAdapter,
    PatchReconstructionHead,
    PhysiologicalRegimeAdapterBank,
    build_patch_missing_mask,
)
from .objectives import (
    FemMHCLosses,
    TemporalOrderHead,
    combine_losses,
    drop_sensor_channels,
    mask_sensor_patches,
    masked_patch_reconstruction_loss,
    preservation_loss,
    sensor_set_consistency_loss,
    temporal_order_loss,
)
from .sensors import (
    MCPHASES_SENSOR_DESCRIPTORS,
    OPENMHC_SENSOR_DESCRIPTORS,
    SensorBatch,
    SensorDescriptor,
    SensorMetadataEncoder,
)
from .tasks import (
    MCPHASES_TASKS,
    McPhasesTaskHeads,
    McPhasesV2TaskHeads,
    NestedHorizonOutput,
    NestedOnsetHead,
    ResidualTaskAdapter,
    TaskDefinition,
    class_balanced_focal_loss,
    cyclic_phase_loss,
    masked_task_loss,
    nested_onset_loss,
)

__all__ = [
    "ClassificationHead",
    "FemMHCEncoder",
    "FemMHCLosses",
    "FemMHCOutput",
    "LifecycleAdapterBank",
    "LowRankAdapter",
    "MCPHASES_SENSOR_DESCRIPTORS",
    "MCPHASES_TASKS",
    "OPENMHC_SENSOR_DESCRIPTORS",
    "McPhasesTaskHeads",
    "McPhasesV2TaskHeads",
    "NestedHorizonOutput",
    "NestedOnsetHead",
    "OrdinalHead",
    "PatchReconstructionHead",
    "PhysiologicalRegimeAdapterBank",
    "ProbabilisticOutput",
    "RegressionHead",
    "ResidualTaskAdapter",
    "SensorBatch",
    "SensorDescriptor",
    "SensorMetadataEncoder",
    "TemporalOrderHead",
    "TaskDefinition",
    "build_patch_missing_mask",
    "combine_losses",
    "class_balanced_focal_loss",
    "cyclic_phase_loss",
    "drop_sensor_channels",
    "mask_sensor_patches",
    "masked_patch_reconstruction_loss",
    "masked_task_loss",
    "nested_onset_loss",
    "preservation_loss",
    "sensor_set_consistency_loss",
    "temporal_order_loss",
]
